version: "3.8"
services: 
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   - MONGODB_USERNAME=root
    #   - MONGODB_PASSWORD=secret
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs    # named volume
      - ./backend:/app    # bind mount
      - /app/node_modules # 익명 volume
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  # frontend:

volumes:
  data:
  logs:
